<html><head><title>Test Output</title></head><body><br><center>TEST CASE RESULTS</center><fieldset><fieldset><div><span>test_a_test (testEx.MyTest)&nbsp;&nbsp;.............................................................................&nbsp;&nbsp;</span><span>FAIL</span><br><br><u>test_a_test (testEx.MyTest)</u><br><pre>Traceback (most recent call last):
  File "C:\Users\DarkPrince\WinPython-64bit-2.7.6.4\python-2.7.6.amd64\lib\unittest\case.py", line 331, in run
    testMethod()
  File "C:\Users\DarkPrince\Desktop\Python Playground\Nose Template\testEx.py", line 8, in test_a_test
    assert False
AssertionError
</pre></div><div><span>test_b_test (testEx.MyTest)&nbsp;&nbsp;.............................................................................&nbsp;&nbsp;</span><span>PASS</span></div><div><span>test_c_test (testEx.MyTest)&nbsp;&nbsp;.............................................................................&nbsp;&nbsp;</span><span>FAIL</span><br><br><u>test_c_test (testEx.MyTest)</u><br><pre>Traceback (most recent call last):
  File "C:\Users\DarkPrince\WinPython-64bit-2.7.6.4\python-2.7.6.amd64\lib\unittest\case.py", line 331, in run
    testMethod()
  File "C:\Users\DarkPrince\Desktop\Python Playground\Nose Template\testEx.py", line 12, in test_c_test
    assert False
AssertionError
</pre></div><div><span>test_d_test (testEx.MyTest)&nbsp;&nbsp;.............................................................................&nbsp;&nbsp;</span><span>PASS</span></div></fieldset></fieldset><div>Ran 4 tests</div><div><span>FAILED ( Failures=2 Errors=0)</span></div></body></html>